# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Welcome to Pantheon Media!
email: subwall@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is all very new to me, so I made this quick site using a tutorial to get 
  myself acquainted with the process.  Hopefully this will become something useful
  one day soon.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
